version: '3.8'
services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    ports:
      - "8001:80"
      - "443:443"
  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password","--max_allowed_packet=1073741824","--wait_timeout=600"]
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
    ports:
        - "3306:3306"
    volumes:
      - ./mysql/db_ar/dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /sessions
